services:
  postgres:
    image: postgres:15-alpine
    container_name: petstore-postgres
    environment:
      POSTGRES_DB: petshopapp
      POSTGRES_USER: techpront
      POSTGRES_PASSWORD: 125322
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - petstore-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U techpront -d petshopapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: petstore-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/petshopapp
      SPRING_DATASOURCE_USERNAME: techpront
      SPRING_DATASOURCE_PASSWORD: 125322
    networks:
      - petstore-network
    restart: unless-stopped
    volumes:
      - app_logs:/app/logs

volumes:
  postgres_data:
  app_logs:

networks:
  petstore-network:
    driver: bridge
